--[[
    CombatSystemServer - 

    System Type: server
    Dependencies: EnemySystem, HeroSystem

    Auto-generated by SystemLuaGen
    DO NOT EDIT MANUALLY (except TODO_LLM sections)
]]

local CombatSystemServer = {}

-- ========== METADATA ==========
CombatSystemServer.name = "CombatSystemServer"
CombatSystemServer.version = "1.0.0"
CombatSystemServer.description = ""
CombatSystemServer.dependencies = { "EnemySystemServer", "HeroSystemServer" }
CombatSystemServer.state = "uninitialized"

-- Framework references
CombatSystemServer.sgf = nil
CombatSystemServer.log = nil
CombatSystemServer.events = nil

-- ========== DATA STORAGE ==========
CombatSystemServer.data = {}

-- Cached dependencies (populated in PostInit)
CombatSystemServer.dependencies_cache = {}

-- ========== CONSTRUCTOR ==========
function CombatSystemServer.new(sgf)
    local self = setmetatable({}, {__index = CombatSystemServer})

    -- Store framework reference
    self.sgf = sgf
    self.log = sgf.log
    self.events = sgf.events

    return self
end

-- ========== LIFECYCLE PHASE 1: PREINIT ==========
--[[
    PreInit - Register event listeners, prepare resources

    Called FIRST, before other systems exist.
    DO NOT access other systems here.
]]
function CombatSystemServer:PreInit()
    self.log:info("[CombatSystemServer] PreInit started")

    -- Register event handlers
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)





    -- Behavior: on_hero_spawned
    self.events:on(EventID.HERO_SPAWNED, function(data)
        self:onHeroSpawned(data)
    end)




    -- Behavior: on_hero_revived
    self.events:on(EventID.HERO_REVIVED, function(data)
        self:onHeroRevived(data)
    end)




    -- Behavior: on_enemy_spawned
    self.events:on(EventID.ENEMY_SPAWNED, function(data)
        self:onEnemySpawned(data)
    end)




    -- Behavior: on_enemy_attacked
    self.events:on(EventID.ENEMY_ATTACKED, function(data)
        self:onEnemyAttacked(data)
    end)









    self.log:info("[CombatSystemServer] PreInit complete")
    return true
end

-- ========== LIFECYCLE PHASE 2: INIT ==========
--[[
    Init - Initialize system, load configuration, register network handlers

    Called SECOND, after all PreInit.
    DO NOT access other systems here (use PostInit).
]]
function CombatSystemServer:Init()
    self.log:info("[CombatSystemServer] Init started")

    -- Load configuration
    self.config = {
        -- TODO: Add configuration values
    }


    -- Register network handlers
    self:registerNetworkHandlers()


    -- Initialize data structures
    -- TODO: Initialize self.data

    self.state = "initialized"
    self.log:info("[CombatSystemServer] Init complete")
    return true
end

-- ========== LIFECYCLE PHASE 3: POSTINIT ==========
--[[
    PostInit - Resolve dependencies on other systems

    Called THIRD, after all Init.
    NOW safe to access other systems.
]]
function CombatSystemServer:PostInit()
    self.log:info("[CombatSystemServer] PostInit started")

    -- Get dependency references

    self.dependencies_cache.EnemySystem = self.sgf.businessSystemManager:get("EnemySystemServer")

    if not self.dependencies_cache.EnemySystem then
        self.log:error("[CombatSystemServer] Missing dependency: EnemySystemServer")
        return false
    end


    self.dependencies_cache.HeroSystem = self.sgf.businessSystemManager:get("HeroSystemServer")

    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Missing dependency: HeroSystemServer")
        return false
    end


    self.log:info("[CombatSystemServer] PostInit complete")
    return true
end

-- ========== LIFECYCLE PHASE 4: START ==========
--[[
    Start - Begin operations, start timers, activate features

    Called FOURTH, after all PostInit.
    All systems are fully initialized.
]]
function CombatSystemServer:Start()
    self.log:info("[CombatSystemServer] Start started")



    -- Behavior: init_combat_system (init)
    self:initCombatSystem()

















    self.state = "started"
    self.log:info("[CombatSystemServer] Started successfully")
    return true
end

-- ========== LIFECYCLE PHASE 5: UPDATE ==========
--[[
    Update - Called every frame

    Optional: Most systems don't need this
]]
function CombatSystemServer:Update(dt)
    -- Optional: Implement frame updates if needed

















end

-- ========== LIFECYCLE PHASE 6: STOP ==========
--[[
    Stop - Clean up resources

    Called when system is shutting down.
]]
function CombatSystemServer:Stop()
    self.log:info("[CombatSystemServer] Stopping...")

    -- TODO: Save data, clean up timers, release resources

    self.state = "stopped"
    self.log:info("[CombatSystemServer] Stopped")
    return true
end


-- ========== NETWORK HANDLERS ==========
function CombatSystemServer:registerNetworkHandlers()
    -- Register as network object
    local NetworkHelper = require(script.Parent.Parent.Parent.GamePlay.NetworkHelper)
    NetworkHelper:RegisterNetObj(self)

    -- Import protocol definitions
    local Protocol = require(script.Parent.Parent.Parent.Runtime.Protocol)


    -- Player action: ACTION_BASIC_ATTACK
    self:OnRequest(Protocol.ClientMSGID.BASIC_ATTACK_REQ, function(userId, msgid, data)
        return self:handleBasicAttack(userId, data)
    end)


    -- Player action: ACTION_HEAVY_ATTACK
    self:OnRequest(Protocol.ClientMSGID.HEAVY_ATTACK_REQ, function(userId, msgid, data)
        return self:handleHeavyAttack(userId, data)
    end)


    -- Player action: ACTION_RANGED_ATTACK
    self:OnRequest(Protocol.ClientMSGID.RANGED_ATTACK_REQ, function(userId, msgid, data)
        return self:handleRangedAttack(userId, data)
    end)


end


-- LLM_IMPL
-- Player Action: ACTION_BASIC_ATTACK
-- Description: Execute a basic melee or ranged attack against the target. Triggers damage calculation and applies damage to target if in range.
function CombatSystemServer:handleBasicAttack(userId, data)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return { success = false, error = "Invalid parameters" }
        end

        -- Extract attack data from request
        local attacker_id = data.attacker_id
        local target_id = data.target_id
        local attack_type = data.attack_type or "melee"

        -- Validate required fields
        if not attacker_id or not target_id then
            self.log:error("handleBasicAttack: Missing attacker_id or target_id")
            return { success = false, error = "Missing attacker or target" }
        end

        -- Check if attacker exists
        if not self.data.CombatState or not self.data.CombatState[attacker_id] then
            self.log:error("handleBasicAttack: Attacker combat state not found for " .. tostring(attacker_id))
            return { success = false, error = "Attacker not found" }
        end

        local attacker_combat_state = self.data.CombatState[attacker_id]

        -- Check if attacker can attack
        if not attacker_combat_state.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack at this time")
            return { success = false, error = "Cannot attack right now" }
        end

        -- Check if target exists
        if not self.data.CombatState or not self.data.CombatState[target_id] then
            self.log:error("handleBasicAttack: Target combat state not found for " .. tostring(target_id))
            return { success = false, error = "Target not found" }
        end

        -- Perform hit detection
        local hit_detection = self:performHitDetection(attacker_id, target_id, attack_type)
        if not hit_detection or not hit_detection.hit_detected then
            self.log:debug("handleBasicAttack: Hit detection failed for attacker " .. tostring(attacker_id))
            return { success = false, error = "Attack missed" }
        end

        -- Calculate damage
        local damage_calc = self:calculateDamage(attacker_id, target_id, attack_type)
        if not damage_calc then
            self.log:error("handleBasicAttack: Damage calculation failed")
            return { success = false, error = "Damage calculation error" }
        end

        -- Apply damage to target
        local apply_result = self:applyDamage(target_id, damage_calc.final_damage, damage_calc.damage_type)
        if not apply_result or not apply_result.success then
            self.log:error("handleBasicAttack: Failed to apply damage to target " .. tostring(target_id))
            return { success = false, error = "Failed to apply damage" }
        end

        -- Update attacker combat state
        attacker_combat_state.last_attack_time = os.time()
        if not attacker_combat_state.in_combat then
            attacker_combat_state.in_combat = true
            attacker_combat_state.combat_start_time = os.time()
        end

        -- Create attack data record
        local attack_data = {
            attacker_id = attacker_id,
            target_id = target_id,
            attack_type = attack_type,
            damage_amount = damage_calc.final_damage,
            timestamp = os.time()
        }

        -- Emit attack event
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        self.events:emit(EventID.EVENT_BASIC_ATTACK, attack_data)

        self.log:info("handleBasicAttack: Attacker " .. tostring(attacker_id) .. " dealt " .. damage_calc.final_damage .. " damage to target " .. tostring(target_id))

        return {
            success = true,
            damage_dealt = damage_calc.final_damage,
end


-- LLM_IMPL
-- Player Action: ACTION_HEAVY_ATTACK
-- Description: Execute a charged heavy attack with increased damage multiplier. Requires longer wind-up but deals significantly more damage.
function CombatSystemServer:handleHeavyAttack(userId, data)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return { success = false, error = "Invalid parameters" }
        end

        -- Get attacker entity
        local attacker = self.data.HeroInstance[userId]
        if not attacker then
            self.log:error("handleBasicAttack: Attacker not found for userId: " .. tostring(userId))
            return { success = false, error = "Attacker not found" }
        end

        -- Validate target exists in data
        local target_id = data.target_id
        if not target_id then
            self.log:error("handleBasicAttack: No target_id provided")
            return { success = false, error = "No target specified" }
        end

        local target = self.data.HeroInstance[target_id]
        if not target then
            self.log:error("handleBasicAttack: Target not found for target_id: " .. tostring(target_id))
            return { success = false, error = "Target not found" }
        end

        -- Check attacker combat state
        local attacker_combat = self.data.CombatState[userId]
        if not attacker_combat then
            self.log:error("handleBasicAttack: Combat state not found for attacker")
            return { success = false, error = "Combat state unavailable" }
        end

        -- Verify attacker can attack
        if not attacker_combat.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack yet")
            return { success = false, error = "Cannot attack at this time" }
        end

        -- Validate attack range (basic check)
        local distance = data.distance or 0
        local max_range = data.attack_range or 5
        if distance > max_range then
            self.log:debug("handleBasicAttack: Target out of range. Distance: " .. distance .. ", Max range: " .. max_range)
            return { success = false, error = "Target out of range" }
        end

        -- Calculate damage
        local base_damage = attacker.attack_power or 10
        local attack_multiplier = data.attack_multiplier or 1.0
        local defense_reduction = target.defense or 0
        local final_damage = math.max(1, math.floor((base_damage * attack_multiplier) - defense_reduction))

        -- Create damage calculation record
        local damage_calc = {
            base_damage = base_damage,
            attack_multiplier = attack_multiplier,
            defense_reduction = defense_reduction,
            final_damage = final_damage,
            damage_type = data.damage_type or "physical"
        }

        -- Apply damage to target
        if target.health then
            target.health = math.max(0, target.health - final_damage)
        end

        -- Update combat states
        attacker_combat.last_attack_time = os.time()
        attacker_combat.in_combat = true
        attacker_combat.combat_start_time = attacker_combat.combat_start_time or os.time()

        local target_combat = self.data.CombatState[target_id]
        if target_combat then
            target_combat.in_combat = true
            target_combat.combat_start_time = target_combat.combat_start_time or os.time()
        end

        -- Create attack data record
        local attack_data = {
            attacker_id = userId,
            target_id = target_id,
            attack_type = data.attack_type or "basic",
            damage_amount = final_damage,
            timestamp = os.time()
        }

        -- Store attack data if table exists
        if not self.data.AttackData then
            self.data.AttackData = {}
        end
        table.insert(self.data.AttackData, attack_data)

        -- Emit attack event
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        if Event
end


-- LLM_IMPL
-- Player Action: ACTION_RANGED_ATTACK
-- Description: Fire a ranged projectile toward target position. Uses raycast for hit detection and applies damage if target is hit.
function CombatSystemServer:handleRangedAttack(userId, data)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return { success = false, error = "Invalid parameters" }
        end

        -- Get attacker entity
        local attacker = self.data.HeroInstance and self.data.HeroInstance[userId]
        if not attacker then
            self.log:error("handleBasicAttack: Attacker not found for userId: " .. tostring(userId))
            return { success = false, error = "Attacker not found" }
        end

        -- Validate target_id exists in data
        if not data.target_id then
            self.log:error("handleBasicAttack: No target_id provided")
            return { success = false, error = "No target specified" }
        end

        -- Get target entity
        local target = self.data.HeroInstance and self.data.HeroInstance[data.target_id]
        if not target then
            self.log:error("handleBasicAttack: Target not found for target_id: " .. tostring(data.target_id))
            return { success = false, error = "Target not found" }
        end

        -- Check combat state of attacker
        local combatState = self.data.CombatState and self.data.CombatState[userId]
        if not combatState then
            self.log:error("handleBasicAttack: Combat state not found for attacker")
            return { success = false, error = "Combat state unavailable" }
        end

        -- Verify attacker can attack
        if not combatState.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack at this time")
            return { success = false, error = "Cannot attack now" }
        end

        -- Perform hit detection if available
        local hitDetection = self.dependencies_cache.HitDetectionSystem
        local hitResult = nil
        if hitDetection then
            hitResult = hitDetection:detectHit(userId, data.target_id, data.attack_type)
            if not hitResult or not hitResult.hit_detected then
                self.log:info("handleBasicAttack: Attack missed for userId: " .. tostring(userId))
                combatState.last_attack_time = os.time()
                return { success = true, hit = false }
            end
        end

        -- Calculate damage
        local damageCalc = self.dependencies_cache.DamageCalculationSystem
        local damageResult = nil
        if damageCalc then
            damageResult = damageCalc:calculateDamage(userId, data.target_id, data.attack_type)
            if not damageResult then
                self.log:error("handleBasicAttack: Damage calculation failed")
                return { success = false, error = "Damage calculation failed" }
            end
        else
            self.log:error("handleBasicAttack: DamageCalculationSystem not available")
            return { success = false, error = "System unavailable" }
        end

        -- Apply damage to target
        if target.health then
            target.health = math.max(0, target.health - damageResult.final_damage)
            self.log:info("handleBasicAttack: Applied " .. tostring(damageResult.final_damage) .. " damage to target")
        end

        -- Update combat state
        combatState.last_attack_time = os.time()
        if not combatState.in_combat then
            combatState.in_combat = true
            combatState.combat_start_time = os.time()
        end

        -- Create attack data for event
        local attackData = {
            attacker_id = userId,
            target_id = data.target_id,
            attack_type = data.attack_type or "basic",
            damage_amount = damageResult.final_damage,
            timestamp = os.time()
        }

        -- Emit attack event
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        if EventID then
end




-- ========== BEHAVIOR HANDLERS (AUTO-GENERATED) ==========



-- Behavior Handler: init_combat_system
-- Trigger: init
-- Summary: Initialize combat system with default damage formulas and attack configurations.
function CombatSystemServer:initCombatSystem()
    -- Behavior steps
    -- Command: CombatSystem.LOAD_COMBAT_CONFIGS
    self:loadCombatConfigs()

    self.log:debug("[CombatSystemServer] init_combat_system completed")
end




-- Behavior Handler: on_hero_spawned
-- Trigger: event HERO_SPAWNED
-- Summary: Initialize combat state for hero when spawned at level start.
function CombatSystemServer:onHeroSpawned(data)
    -- Behavior steps
    -- Command: CombatSystem.INIT_COMBAT_STATE
    self:initCombatState(data.hero_id, data.hero)

    -- Emit event: COMBAT_STARTED
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
    self.events:emit(EventID.COMBAT_STARTED, {
        entity_id = data.hero_id,
        opponent_id = data.null,
    })

    self.log:debug("[CombatSystemServer] on_hero_spawned completed")
end




-- Behavior Handler: on_hero_revived
-- Trigger: event HERO_REVIVED
-- Summary: Reset hero combat state after revival, clearing combat flags and cooldowns.
function CombatSystemServer:onHeroRevived(data)
    -- Behavior steps
    -- Command: CombatSystem.RESET_COMBAT_STATE
    self:recombatState(data.hero_id)

    -- Emit event: COMBAT_ENDED
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
    self.events:emit(EventID.COMBAT_ENDED, {
        entity_id = data.hero_id,
        duration = 0,
    })

    self.log:debug("[CombatSystemServer] on_hero_revived completed")
end




-- Behavior Handler: on_enemy_spawned
-- Trigger: event ENEMY_SPAWNED
-- Summary: Initialize combat state for newly spawned enemy.
function CombatSystemServer:onEnemySpawned(data)
    -- Behavior steps
    -- Command: CombatSystem.INIT_COMBAT_STATE
    self:initCombatState(data.enemy_id, data.enemy)

    self.log:debug("[CombatSystemServer] on_enemy_spawned completed")
end




-- Behavior Handler: on_enemy_attacked
-- Trigger: event ENEMY_ATTACKED
-- Summary: Process enemy attack on hero by calculating and applying damage.
function CombatSystemServer:onEnemyAttacked(data)
    -- Behavior steps
    -- Query: EnemySystem.get_enemy_stats
    if not self.dependencies_cache.EnemySystem then
        self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
        return
    end
    local enemy_stats = self.dependencies_cache.EnemySystem:getEnemyStats(data.enemy_id)

    -- Query: HeroSystem.get_hero_defense
    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
        return
    end
    local hero_defense = self.dependencies_cache.HeroSystem:getHeroDefense()

    -- Query: CombatSystem.get_damage_for_attack
    local damage_amount = self:getDamageForAttack(data.enemy_id, data.attack_type)

    -- Command: CombatSystem.APPLY_DAMAGE
    self:applyDamage(data.hero, damage_amount, data.physical, data.enemy_id)

    -- Emit event: DAMAGE_DEALT
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
    self.events:emit(EventID.DAMAGE_DEALT, {
        attacker_id = data.enemy_id,
        target_id = data.hero,
        damage_amount = damage_amount,
        damage_type = data.physical,
    })

    -- Query: HeroSystem.get_hero_health
    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
        return
    end
    local current_health = self.dependencies_cache.HeroSystem:getHeroHealth()

    -- Conditional: current_health <= 0
    if current_health <= 0 then
        -- Command: CombatSystem.REGISTER_DEATH
        self:registerDeath(data.hero)

        -- Query: HeroSystem.get_hero_position
        if not self.dependencies_cache.HeroSystem then
            self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
            return
        end
        local death_position = self.dependencies_cache.HeroSystem:getHeroPosition()

        -- Emit event: HERO_DIED
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        self.events:emit(EventID.HERO_DIED, {
            hero_id = data.hero,
            killer_id = data.enemy_id,
            position = data.death_position,
        })
    end

    self.log:debug("[CombatSystemServer] on_enemy_attacked completed")
end




-- Behavior Handler: on_basic_attack
-- Trigger: player action ACTION_BASIC_ATTACK
-- Summary: Handle player basic attack input by performing hit detection and applying damage.
function CombatSystemServer:onBasicAttack(userId, data)
    -- Behavior steps
    -- Query: HeroSystem.can_hero_act
    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
        return
    end
    local can_act = self.dependencies_cache.HeroSystem:canHeroAct()

    -- Conditional: can_act == true
    if can_act == true then
        -- Query: CombatSystem.is_in_attack_range
        local in_range = self:isInAttackRange(hero, target_id, basic)

        -- Conditional: in_range == true
        if in_range == true then
            -- Query: HeroSystem.get_hero_attack_power
            if not self.dependencies_cache.HeroSystem then
                self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
                return
            end
            local attack_power = self.dependencies_cache.HeroSystem:getHeroAttackPower()

            -- Query: EnemySystem.get_enemy_stats
            if not self.dependencies_cache.EnemySystem then
                self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                return
            end
            local target_stats = self.dependencies_cache.EnemySystem:getEnemyStats(target_id)

            -- Query: CombatSystem.get_damage_for_attack
            local damage = self:getDamageForAttack(hero, basic)

            -- Command: CombatSystem.APPLY_DAMAGE
            self:applyDamage(target_id, damage, physical, hero)

            -- Emit event: ATTACK_EXECUTED
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.ATTACK_EXECUTED, {
                attacker_id = hero,
                target_id = target_id,
                attack_type = basic,
                success = true,
            })

            -- Emit event: DAMAGE_DEALT
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.DAMAGE_DEALT, {
                attacker_id = hero,
                target_id = target_id,
                damage_amount = damage,
                damage_type = physical,
            })

            -- Command: EnemySystem.UPDATE_ENEMY_HEALTH
            if not self.dependencies_cache.EnemySystem then
                self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                return
            end
            self.dependencies_cache.EnemySystem:updateEnemyHealth(target_id, target_stats.health - damage)

            -- Query: EnemySystem.get_enemy_health
            if not self.dependencies_cache.EnemySystem then
                self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                return
            end
            local target_health = self.dependencies_cache.EnemySystem:getEnemyHealth(target_id)

            -- Conditional: target_health <= 0
            if target_health <= 0 then
                -- Command: CombatSystem.REGISTER_DEATH
                self:registerDeath(target_id)

                -- Query: EnemySystem.get_enemy_position
                if not self.dependencies_cache.EnemySystem then
                    self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                    return
                end
                local enemy_position = self.dependencies_cache.EnemySystem:getEnemyPosition(target_id)

                -- Emit event: ENEMY_DEFEATED
                local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
                self.events:emit(EventID.ENEMY_DEFEATED, {
                    enemy_id = target_id,
                    hero_id = hero,
                    position = enemy_position,
                })

                -- Command: EnemySystem.DESPAWN_ENEMY
                if not self.dependencies_cache.EnemySystem then
                    self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                    return
                end
                self.dependencies_cache.EnemySystem:despawnEnemy(target_id)
            end
        end
    end

    self.log:debug("[CombatSystemServer] on_basic_attack completed")
end




-- Behavior Handler: on_heavy_attack
-- Trigger: player action ACTION_HEAVY_ATTACK
-- Summary: Handle player heavy attack with increased damage multiplier and longer wind-up.
function CombatSystemServer:onHeavyAttack(userId, data)
    -- Behavior steps
    -- Query: HeroSystem.can_hero_act
    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
        return
    end
    local can_act = self.dependencies_cache.HeroSystem:canHeroAct()

    -- Conditional: can_act == true
    if can_act == true then
        -- Query: CombatSystem.is_in_attack_range
        local in_range = self:isInAttackRange(hero, target_id, heavy)

        -- Conditional: in_range == true
        if in_range == true then
            -- Query: CombatSystem.get_damage_for_attack
            local damage = self:getDamageForAttack(hero, heavy)

            -- Command: CombatSystem.APPLY_DAMAGE
            self:applyDamage(target_id, damage, physical, hero)

            -- Emit event: ATTACK_EXECUTED
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.ATTACK_EXECUTED, {
                attacker_id = hero,
                target_id = target_id,
                attack_type = heavy,
                success = true,
            })

            -- Emit event: DAMAGE_DEALT
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.DAMAGE_DEALT, {
                attacker_id = hero,
                target_id = target_id,
                damage_amount = damage,
                damage_type = physical,
            })

            -- Query: EnemySystem.get_enemy_health
            if not self.dependencies_cache.EnemySystem then
                self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                return
            end
            local target_health = self.dependencies_cache.EnemySystem:getEnemyHealth(target_id)

            -- Conditional: target_health <= 0
            if target_health <= 0 then
                -- Command: CombatSystem.REGISTER_DEATH
                self:registerDeath(target_id)

                -- Query: EnemySystem.get_enemy_position
                if not self.dependencies_cache.EnemySystem then
                    self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                    return
                end
                local enemy_position = self.dependencies_cache.EnemySystem:getEnemyPosition(target_id)

                -- Emit event: ENEMY_DEFEATED
                local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
                self.events:emit(EventID.ENEMY_DEFEATED, {
                    enemy_id = target_id,
                    hero_id = hero,
                    position = enemy_position,
                })

                -- Command: EnemySystem.DESPAWN_ENEMY
                if not self.dependencies_cache.EnemySystem then
                    self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                    return
                end
                self.dependencies_cache.EnemySystem:despawnEnemy(target_id)
            end
        end
    end

    self.log:debug("[CombatSystemServer] on_heavy_attack completed")
end




-- Behavior Handler: on_ranged_attack
-- Trigger: player action ACTION_RANGED_ATTACK
-- Summary: Handle player ranged attack using raycast hit detection toward target position.
function CombatSystemServer:onRangedAttack(userId, data)
    -- Behavior steps
    -- Query: HeroSystem.can_hero_act
    if not self.dependencies_cache.HeroSystem then
        self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
        return
    end
    local can_act = self.dependencies_cache.HeroSystem:canHeroAct()

    -- Conditional: can_act == true
    if can_act == true then
        -- Query: HeroSystem.get_hero_position
        if not self.dependencies_cache.HeroSystem then
            self.log:error("[CombatSystemServer] Dependency not available: HeroSystem")
            return
        end
        local hero_position = self.dependencies_cache.HeroSystem:getHeroPosition()

        -- Command: CombatSystem.PERFORM_RAYCAST
        self:performRaycast(hero_position, target_position)

        -- Query: CombatSystem.get_raycast_result
        local hit_result = self:getRaycastResult()

        -- Conditional: hit_result.hit_detected == true
        if hit_result.hit_detected == true then
            -- Query: CombatSystem.get_damage_for_attack
            local damage = self:getDamageForAttack(hero, ranged)

            -- Command: CombatSystem.APPLY_DAMAGE
            self:applyDamage(hit_result.hit_entity_id, damage, physical, hero)

            -- Emit event: ATTACK_EXECUTED
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.ATTACK_EXECUTED, {
                attacker_id = hero,
                target_id = hit_result.hit_entity_id,
                attack_type = ranged,
                success = true,
            })

            -- Emit event: DAMAGE_DEALT
            local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
            self.events:emit(EventID.DAMAGE_DEALT, {
                attacker_id = hero,
                target_id = hit_result.hit_entity_id,
                damage_amount = damage,
                damage_type = physical,
            })

            -- Query: EnemySystem.get_enemy_health
            if not self.dependencies_cache.EnemySystem then
                self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                return
            end
            local target_health = self.dependencies_cache.EnemySystem:getEnemyHealth(hit_result.hit_entity_id)

            -- Conditional: target_health <= 0
            if target_health <= 0 then
                -- Command: CombatSystem.REGISTER_DEATH
                self:registerDeath(hit_result.hit_entity_id)

                -- Emit event: ENEMY_DEFEATED
                local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
                self.events:emit(EventID.ENEMY_DEFEATED, {
                    enemy_id = hit_result.hit_entity_id,
                    hero_id = hero,
                    position = hit_result.hit_position,
                })

                -- Command: EnemySystem.DESPAWN_ENEMY
                if not self.dependencies_cache.EnemySystem then
                    self.log:error("[CombatSystemServer] Dependency not available: EnemySystem")
                    return
                end
                self.dependencies_cache.EnemySystem:despawnEnemy(hit_result.hit_entity_id)
            end
        end
    end

    self.log:debug("[CombatSystemServer] on_ranged_attack completed")
end



-- ========== QUERIES (LLM-IMPLEMENTED) ==========


-- LLM_IMPL
-- Query: get_damage_for_attack(attacker_id, attack_type) -> int
-- Description: Calculate the expected damage for an attack type based on attacker's stats and attack multipliers.
function CombatSystemServer:getDamageForAttack(attacker_id, attack_type)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return 0
        end

        local attacker_id = data.attacker_id
        local target_id = data.target_id
        local attack_type = data.attack_type

        -- Validate attacker and target exist
        if not attacker_id or not target_id then
            self.log:error("handleBasicAttack: Missing attacker_id or target_id")
            return 0
        end

        if not attack_type then
            self.log:error("handleBasicAttack: Missing attack_type")
            return 0
        end

        -- Check if attacker exists in combat state
        local attacker_combat = self.data.CombatState and self.data.CombatState[attacker_id]
        if not attacker_combat then
            self.log:debug("handleBasicAttack: Attacker not in combat state")
            return 0
        end

        -- Check if attacker can currently attack
        if not attacker_combat.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack at this time")
            return 0
        end

        -- Check if target exists in combat state
        local target_combat = self.data.CombatState and self.data.CombatState[target_id]
        if not target_combat then
            self.log:debug("handleBasicAttack: Target not in combat state")
            return 0
        end

        -- Get attacker and target hero instances for stat lookup
        local attacker = self.data.HeroInstance and self.data.HeroInstance[attacker_id]
        local target = self.data.HeroInstance and self.data.HeroInstance[target_id]

        if not attacker or not target then
            self.log:error("handleBasicAttack: Could not find attacker or target hero instance")
            return 0
        end

        -- Calculate base damage based on attack type
        local base_damage = 0
        if attack_type == "melee" then
            base_damage = attacker.attack_power or 10
        elseif attack_type == "ranged" then
            base_damage = math.floor((attacker.attack_power or 10) * 0.9)
        else
            self.log:error("handleBasicAttack: Unknown attack_type: " .. tostring(attack_type))
            return 0
        end

        -- Get attack multiplier (can vary based on weapon, buffs, etc.)
        local attack_multiplier = 1.0

        -- Calculate defense reduction from target
        local target_defense = target.defense or 0
        local defense_reduction = math.max(0, target_defense * 0.1)

        -- Calculate final damage
        local final_damage = math.floor((base_damage * attack_multiplier) - defense_reduction)
        final_damage = math.max(1, final_damage) -- Ensure minimum 1 damage

        -- Store damage calculation for reference
        if not self.data.DamageCalculation then
            self.data.DamageCalculation = {}
        end

        self.data.DamageCalculation[attacker_id] = {
            base_damage = base_damage,
            attack_multiplier = attack_multiplier,
            defense_reduction = defense_reduction,
            final_damage = final_damage,
            damage_type = attack_type
        }

        self.log:info("handleBasicAttack: Attacker " .. tostring(attacker_id) .. 
                      " dealt " .. tostring(final_damage) .. " damage to target " .. 
                      tostring(target_id) .. " using " .. attack_type .. " attack")

        return final_damage
end


-- LLM_IMPL
-- Query: is_in_attack_range(attacker_id, target_id, attack_type) -> bool
-- Description: Check if target is within valid attack range for the specified attack type (melee or ranged).
function CombatSystemServer:isInAttackRange(attacker_id, target_id, attack_type)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return 0
        end

        if not data.attacker_id or not data.target_id then
            self.log:error("handleBasicAttack: Missing attacker_id or target_id in data")
            return 0
        end

        -- Get attacker entity
        local attacker = self.data.HeroInstance and self.data.HeroInstance[data.attacker_id]
        if not attacker then
            self.log:error("handleBasicAttack: Attacker not found - " .. tostring(data.attacker_id))
            return 0
        end

        -- Get target entity
        local target = self.data.HeroInstance and self.data.HeroInstance[data.target_id]
        if not target then
            self.log:error("handleBasicAttack: Target not found - " .. tostring(data.target_id))
            return 0
        end

        -- Get combat state for attacker
        local attackerCombatState = self.data.CombatState and self.data.CombatState[data.attacker_id]
        if not attackerCombatState then
            self.log:error("handleBasicAttack: Attacker combat state not found")
            return 0
        end

        -- Check if attacker can attack
        if not attackerCombatState.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack at this time")
            return 0
        end

        -- Check attack range
        local attackRange = 5.0 -- Default melee range
        if data.attack_type == "ranged" then
            attackRange = 15.0
        end

        local distance = (attacker.position - target.position).magnitude
        if distance > attackRange then
            self.log:debug("handleBasicAttack: Target out of range. Distance: " .. tostring(distance) .. ", Range: " .. tostring(attackRange))
            return 0
        end

        -- Calculate damage
        local baseDamage = attacker.attack_power or 10
        local attackMultiplier = 1.0
        local defenseReduction = target.defense or 0

        if data.attack_type == "ranged" then
            attackMultiplier = 0.8
        end

        local calculatedDamage = math.floor(baseDamage * attackMultiplier - (defenseReduction * 0.1))
        calculatedDamage = math.max(1, calculatedDamage) -- Minimum 1 damage

        -- Apply damage to target
        if target.health then
            target.health = target.health - calculatedDamage
            if target.health < 0 then
                target.health = 0
            end
        end

        -- Update combat state
        attackerCombatState.last_attack_time = os.time()
        attackerCombatState.in_combat = true

        -- Log the attack
        self.log:info("handleBasicAttack: Attacker " .. tostring(data.attacker_id) .. " dealt " .. tostring(calculatedDamage) .. " damage to target " .. tostring(data.target_id))

        -- Emit attack event
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        if EventID then
            self.events:emit(EventID.ACTION_BASIC_ATTACK, {
                attacker_id = data.attacker_id,
                target_id = data.target_id,
                damage_amount = calculatedDamage,
                attack_type = data.attack_type,
                timestamp = os.time()
            })
        end

        return calculatedDamage
end


-- LLM_IMPL
-- Query: get_combat_state(entity_id) -> string
-- Description: Get current combat state of entity (in_combat, can_attack, cooldown, etc.).
function CombatSystemServer:getCombatState(entity_id)
    -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Invalid parameters - userId or data is nil")
            return false
        end

        local attacker_id = data.attacker_id
        local target_id = data.target_id
        local attack_type = data.attack_type

        -- Validate required attack data
        if not attacker_id or not target_id or not attack_type then
            self.log:error("handleBasicAttack: Missing required attack data")
            return false
        end

        -- Check if attacker exists
        if not self.data.CombatState or not self.data.CombatState[attacker_id] then
            self.log:error("handleBasicAttack: Attacker combat state not found for id: " .. tostring(attacker_id))
            return false
        end

        local attacker_state = self.data.CombatState[attacker_id]

        -- Check if attacker can attack
        if not attacker_state.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack at this time")
            return false
        end

        -- Check if target exists
        if not self.data.CombatState or not self.data.CombatState[target_id] then
            self.log:error("handleBasicAttack: Target combat state not found for id: " .. tostring(target_id))
            return false
        end

        local target_state = self.data.CombatState[target_id]

        -- Perform hit detection
        local hit_result = self:performHitDetection(attacker_id, target_id, attack_type)
        if not hit_result or not hit_result.hit_detected then
            self.log:debug("handleBasicAttack: Hit detection failed")
            return false
        end

        -- Check if target is in range
        if hit_result.hit_distance and hit_result.hit_distance > self:getAttackRange(attack_type) then
            self.log:debug("handleBasicAttack: Target out of range. Distance: " .. tostring(hit_result.hit_distance))
            return false
        end

        -- Calculate damage
        local damage_calc = self:calculateDamage(attacker_id, target_id, attack_type)
        if not damage_calc or damage_calc.final_damage <= 0 then
            self.log:debug("handleBasicAttack: Damage calculation resulted in no damage")
            return false
        end

        -- Apply damage to target
        local damage_applied = self:applyDamage(target_id, damage_calc.final_damage, damage_calc.damage_type)
        if not damage_applied then
            self.log:error("handleBasicAttack: Failed to apply damage to target")
            return false
        end

        -- Update attacker combat state
        attacker_state.last_attack_time = os.time()
        attacker_state.in_combat = true

        -- Update target combat state
        target_state.in_combat = true
        target_state.combat_start_time = os.time()

        -- Create attack data record
        local attack_data = {
            attacker_id = attacker_id,
            target_id = target_id,
            attack_type = attack_type,
            damage_amount = damage_calc.final_damage,
            timestamp = os.time()
        }

        if not self.data.AttackData then
            self.data.AttackData = {}
        end
        table.insert(self.data.AttackData, attack_data)

        -- Emit attack event
        local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)
        if EventID then
            self.events:emit(EventID.ACTION_BASIC_ATTACK, {
                attacker_id = attacker_id,
                target_id = target_id,
                attack_
end


-- ========== COMMANDS (LLM-IMPLEMENTED) ==========


-- LLM_IMPL
-- Command: APPLY_DAMAGE(target_id, amount, damage_type, source_id) -> void
-- Description: Apply calculated damage to target entity. Updates health and triggers death if health reaches zero.

function CombatSystemServer:applyDamage(target_id, amount, damage_type, source_id)
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)

        -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return false
        end

        local attacker_id = data.attacker_id
        local target_id = data.target_id
        local attack_type = data.attack_type

        -- Validate required fields
        if not attacker_id or not target_id or not attack_type then
            self.log:error("handleBasicAttack: Missing required attack parameters")
            return false
        end

        -- Get attacker entity
        local attacker = self.data.HeroInstance and self.data.HeroInstance[attacker_id]
        if not attacker then
            self.log:error("handleBasicAttack: Attacker not found - " .. tostring(attacker_id))
            return false
        end

        -- Get target entity
        local target = self.data.HeroInstance and self.data.HeroInstance[target_id]
        if not target then
            self.log:error("handleBasicAttack: Target not found - " .. tostring(target_id))
            return false
        end

        -- Get or create combat state for attacker
        if not self.data.CombatState then
            self.data.CombatState = {}
        end

        local attacker_combat_state = self.data.CombatState[attacker_id]
        if not attacker_combat_state then
            attacker_combat_state = {
                entity_id = attacker_id,
                in_combat = false,
                combat_start_time = 0,
                last_attack_time = 0,
                can_attack = true
            }
            self.data.CombatState[attacker_id] = attacker_combat_state
        end

        -- Check if attacker can attack
        if not attacker_combat_state.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack - cooldown active")
            return false
        end

        -- Perform hit detection
        local hit_detection = self:performHitDetection(attacker_id, target_id, attack_type)
        if not hit_detection or not hit_detection.hit_detected then
            self.log:debug("handleBasicAttack: Hit detection failed")
            self.events:emit(EventID.ACTION_BASIC_ATTACK_MISS, {
                attacker_id = attacker_id,
                target_id = target_id,
                attack_type = attack_type,
                timestamp = os.time()
            })
            return false
        end

        -- Calculate damage
        local damage_calc = self:calculateDamage(attacker_id, target_id, attack_type)
        if not damage_calc then
            self.log:error("handleBasicAttack: Damage calculation failed")
            return false
        end

        -- Apply damage to target
        local damage_applied = self:applyDamage(target_id, damage_calc.final_damage, damage_calc.damage_type)
        if not damage_applied then
            self.log:error("handleBasicAttack: Failed to apply damage to target")
            return false
        end

        -- Update combat states
        local current_time = os.time()
        attacker_combat_state.in_combat = true
        attacker_combat_state.combat_start_time = attacker_combat_state.combat_start_time > 0 and attacker_combat_state.combat_start_time or current_time
        attacker_combat_state.last_attack_time = current_time
        attacker_combat_state.can_attack = false

        -- Get or create combat state for target
        local target_combat_state = self.data.CombatState[target_id]
        if not target_combat_state then
            target_combat_state = {
                entity_i
end


-- LLM_IMPL
-- Command: EXECUTE_ATTACK(attacker_id, target_id, attack_type) -> void
-- Description: Execute an attack from attacker to target. Performs hit detection, calculates damage, and applies effects.

function CombatSystemServer:executeAttack(attacker_id, target_id, attack_type)
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)

        -- Validate input parameters
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return false
        end

        local attacker_id = data.attacker_id
        local target_id = data.target_id
        local attack_type = data.attack_type

        -- Validate required fields
        if not attacker_id or not target_id or not attack_type then
            self.log:error("handleBasicAttack: Missing required attack parameters")
            return false
        end

        -- Check if attacker exists
        local attacker = self.data.HeroInstance and self.data.HeroInstance[attacker_id]
        if not attacker then
            self.log:error("handleBasicAttack: Attacker not found - " .. tostring(attacker_id))
            return false
        end

        -- Check if target exists
        local target = self.data.HeroInstance and self.data.HeroInstance[target_id]
        if not target then
            self.log:error("handleBasicAttack: Target not found - " .. tostring(target_id))
            return false
        end

        -- Get or initialize combat state for attacker
        if not self.data.CombatState then
            self.data.CombatState = {}
        end

        local attacker_combat_state = self.data.CombatState[attacker_id]
        if not attacker_combat_state then
            attacker_combat_state = {
                entity_id = attacker_id,
                in_combat = false,
                combat_start_time = 0,
                last_attack_time = 0,
                can_attack = true
            }
            self.data.CombatState[attacker_id] = attacker_combat_state
        end

        -- Check if attacker can attack
        if not attacker_combat_state.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack - cooldown active")
            return false
        end

        local current_time = os.time()

        -- Perform hit detection
        local hit_result = self:performHitDetection(attacker_id, target_id, attack_type)
        if not hit_result or not hit_result.hit_detected then
            self.log:info("handleBasicAttack: Attack missed - attacker: " .. tostring(attacker_id) .. ", target: " .. tostring(target_id))

            -- Emit miss event
            self.events:emit(EventID.ACTION_BASIC_ATTACK_MISS, {
                attacker_id = attacker_id,
                target_id = target_id,
                attack_type = attack_type,
                timestamp = current_time
            })

            return false
        end

        -- Calculate damage
        local damage_calc = self:calculateDamage(attacker_id, target_id, attack_type)
        if not damage_calc then
            self.log:error("handleBasicAttack: Damage calculation failed")
            return false
        end

        local final_damage = damage_calc.final_damage

        -- Apply damage to target
        if target.health then
            target.health = math.max(0, target.health - final_damage)
        end

        -- Create attack data record
        local attack_data = {
            attacker_id = attacker_id,
            target_id = target_id,
            attack_type = attack_type,
            damage_amount = final_damage,
            timestamp = current_time
        }

        if not self.data.AttackData then
            self.data.AttackData = {}
        end
        table.insert(self.data.AttackData, attack_data)

        -- Update combat states
        attacker_combat_state.in_combat = true
        attacker_combat_state.
end


-- LLM_IMPL
-- Command: REGISTER_DEATH(entity_id) -> void
-- Description: Register entity death and trigger appropriate death handling and respawn events.

function CombatSystemServer:registerDeath(entity_id)
    local EventID = require(script.Parent.Parent.Parent.Runtime.EventID)

        -- Validate inputs
        if not userId or not data then
            self.log:error("handleBasicAttack: Missing userId or data")
            return "ERROR_INVALID_INPUT"
        end

        if not data.entity_id then
            self.log:error("handleBasicAttack: Missing entity_id in data")
            return "ERROR_MISSING_TARGET"
        end

        local attacker_id = userId
        local target_id = data.entity_id

        -- Check if attacker exists and is in valid state
        if not self.data.CombatState or not self.data.CombatState[attacker_id] then
            self.log:error("handleBasicAttack: Attacker combat state not found for " .. tostring(attacker_id))
            return "ERROR_ATTACKER_NOT_FOUND"
        end

        local attacker_state = self.data.CombatState[attacker_id]

        -- Check if attacker can attack
        if not attacker_state.can_attack then
            self.log:debug("handleBasicAttack: Attacker cannot attack yet")
            return "ERROR_CANNOT_ATTACK"
        end

        -- Check if target exists
        if not self.data.CombatState or not self.data.CombatState[target_id] then
            self.log:error("handleBasicAttack: Target combat state not found for " .. tostring(target_id))
            return "ERROR_TARGET_NOT_FOUND"
        end

        local target_state = self.data.CombatState[target_id]

        -- Perform hit detection
        local hit_result = self:performHitDetection(attacker_id, target_id)

        if not hit_result or not hit_result.hit_detected then
            self.log:info("handleBasicAttack: Attack missed from " .. tostring(attacker_id) .. " to " .. tostring(target_id))
            self.events:emit(EventID.ATTACK_MISSED, {
                attacker_id = attacker_id,
                target_id = target_id,
                timestamp = os.time()
            })
            return "ATTACK_MISSED"
        end

        -- Calculate damage
        local damage_calc = self:calculateDamage(attacker_id, target_id)

        if not damage_calc then
            self.log:error("handleBasicAttack: Damage calculation failed")
            return "ERROR_DAMAGE_CALCULATION"
        end

        local final_damage = damage_calc.final_damage

        -- Create attack data record
        local attack_data = {
            attacker_id = attacker_id,
            target_id = target_id,
            attack_type = "BASIC_ATTACK",
            damage_amount = final_damage,
            timestamp = os.time()
        }

        -- Store attack data
        if not self.data.AttackData then
            self.data.AttackData = {}
        end
        table.insert(self.data.AttackData, attack_data)

        -- Apply damage to target
        local damage_applied = self:applyDamage(target_id, final_damage)

        if not damage_applied then
            self.log:error("handleBasicAttack: Failed to apply damage to target")
            return "ERROR_APPLY_DAMAGE"
        end

        -- Update attacker combat state
        attacker_state.last_attack_time = os.time()
        attacker_state.can_attack = false
        if not attacker_state.in_combat then
            attacker_state.in_combat = true
            attacker_state.combat_start_time = os.time()
        end

        -- Update target combat state
        if not target_state.in_combat then
            target_state.in_combat = true
            target_state.combat_start_time
end


-- ========== HELPER METHODS (STUBS) ==========


return CombatSystemServer