return {
    bb = {
        RT_EnterCombatLocation = {0,0,0},
        CombatRadius = 3000,
        RandomMove_Radius = 1000,
        RandomMove_Interval = 5,
        Follow_Radius = 1000,
        Follow_Interval = 5,
        RT_Target = nil,
        Attack_Radius = 200,
        Attack_GazeAngle = 90,
        Attack_Skill1_Range = {0,500},
        Attack_Skill1_Chance = 100,
        Attack_Skill1_Cooldown = 4,
        Attack_Skill2_Range = {0,500},
        Attack_Skill2_Chance = 0,
        Attack_Skill2_Cooldown = 3,
        Attack_Skill3_Range = {0,500},
        Attack_Skill3_Chance = 0,
        Attack_Skill3_Cooldown = 5,
        Attack_Skill4_Range = {0,500},
        Attack_Skill4_Chance = 0,
        Attack_Skill4_Cooldown = 10,
        Approach_Acceptance = 200,
        RT_Self = nil,
        RT_Master = nil,
        RT_BornPosition = {0,0,0},
        RT_Behavior = "behavior",
        DefaultBehavior = "Idle",
        RT_TargetLocation = {0,0,0},
        LocationErr = 100,
        note = "",
    },
    behavior = {
        name = "Selector",
        decorators = {
        },
        service = {
            name = "WarriorService",
            args = {
                targetBBKey = "RT_Target",
                masterBBKey = "RT_Master",
                enterCombatLocationBBKey = "RT_EnterCombatLocation",
                combatRadius = 10,
                combatRadiusBBKey = "CombatRadius",
                attackRadius = 10,
                attackRadiusBBKey = "Attack_Radius",
                disableApproach = false,
                disableAttack = false,
                selfBBKey = "RT_Self",
                behaviorBBKey = "RT_Behavior",
                defaultBehaviorBBKey = "DefaultBehavior",
                bornBBKey = "RT_BornPosition",
                note = "",
            },
        },
        children = {
            {
                name = "Selector",
                decorators = {
                },
                args = {
                    canInterrupt = true,
                    note = "",
                },
                children = {
                },
            },
        },
    },
}
