local Class = GFScript("CoreModule.Class")
local Utils = GFScript("CoreModule.Utils")
local Log = GFScript("CoreModule.Log")
local BehaviorDefines = GFScript("AIModule.BTree.BehaviorDefines")
local BehaviorNode = GFScript("AIModule.BTree.BehaviorNode")
local BehaviorTree = GFScript("AIModule.BTree.BehaviorTree")

local GenericTree = Class.New("GenericTree", BehaviorTree)
--注册所有节点信息
BehaviorTree.process["FindNextPatrolLocation"] =    GFScript("AIModule.Generic.EQS.FindNextPatrolLocation")
BehaviorTree.process["FindRandomLocation"] =        GFScript("AIModule.Generic.EQS.FindRandomLocation")
BehaviorTree.process["FindRandomLocationInArea"] =  GFScript("AIModule.Generic.EQS.FindRandomLocationInArea")
BehaviorTree.process["FindFanLocation"] =           GFScript("AIModule.Generic.EQS.FindFanLocation")
BehaviorTree.process["FindLocation"] =              GFScript("AIModule.Generic.EQS.FindLocation")
BehaviorTree.process["FindNextWaypoint"] =          GFScript("AIModule.Generic.EQS.FindNextWaypoint")
BehaviorTree.process["FindOffsetLocation"] =        GFScript("AIModule.Generic.EQS.FindOffsetLocation")

BehaviorTree.process["MoveToLocation"] =            GFScript("AIModule.Generic.Actions.MoveToLocation")
BehaviorTree.process["MoveByLocation"] =            GFScript("AIModule.Generic.Actions.MoveByLocation")
BehaviorTree.process["MoveToTarget"] =              GFScript("AIModule.Generic.Actions.MoveToTarget")
BehaviorTree.process["MoveToWaypoint"] =            GFScript("AIModule.Generic.Actions.MoveToWaypoint")
BehaviorTree.process["NavigateToLocation"] =        GFScript("AIModule.Generic.Actions.NavigateToLocation")
BehaviorTree.process["RotateToTarget"] =            GFScript("AIModule.Generic.Actions.RotateToTarget")
BehaviorTree.process["FaceToTarget"] =              GFScript("AIModule.Generic.Actions.FaceToTarget")
BehaviorTree.process["Attack"] =                    GFScript("AIModule.Generic.Actions.Attack")
BehaviorTree.process["ComboAttack"] =               GFScript("AIModule.Generic.Actions.ComboAttack")
BehaviorTree.process["SetMovementState"] =          GFScript("AIModule.Generic.Actions.SetMovementState")
BehaviorTree.process["PlayMontage"] =               GFScript("AIModule.Generic.Actions.PlayMontage")
BehaviorTree.process["InteractToWaypoint"] =        GFScript("AIModule.Generic.Actions.InteractToWaypoint")
BehaviorTree.process["ChangeBehavior"] =            GFScript("AIModule.Generic.Actions.ChangeBehavior")
BehaviorTree.process["AddBuff"] =                   GFScript("AIModule.Generic.Actions.AddBuff")
BehaviorTree.process["DispelBuff"] =                GFScript("AIModule.Generic.Actions.DispelBuff")
BehaviorTree.process["RemoveBuff"] =                GFScript("AIModule.Generic.Actions.RemoveBuff")
BehaviorTree.process["Teleport"] =                  GFScript("AIModule.Generic.Actions.Teleport")
BehaviorTree.process["KillSelf"] =                  GFScript("AIModule.Generic.Actions.KillSelf")
BehaviorTree.process["GoHome"] =                    GFScript("AIModule.Generic.Actions.GoHome")
BehaviorTree.process["AimToTarget"] =               GFScript("AIModule.Generic.Actions.AimToTarget")
BehaviorTree.process["Shot"] =                      GFScript("AIModule.Generic.Actions.Shot")

BehaviorTree.process["Cooldown"] =                  GFScript("AIModule.Generic.Decorators.Cooldown")
BehaviorTree.process["Chance"] =                    GFScript("AIModule.Generic.Decorators.Chance")
BehaviorTree.process["InRangeToTarget"] =           GFScript("AIModule.Generic.Decorators.InRangeToTarget")
BehaviorTree.process["InRangeToLocation"] =         GFScript("AIModule.Generic.Decorators.InRangeToLocation")
BehaviorTree.process["CheckProjectile"] =           GFScript("AIModule.Generic.Decorators.CheckProjectile")
BehaviorTree.process["InAngleToTarget"] =           GFScript("AIModule.Generic.Decorators.InAngleToTarget")
BehaviorTree.process["TargetState"] =               GFScript("AIModule.Generic.Decorators.TargetState")
BehaviorTree.process["InRangeHealth"] =             GFScript("AIModule.Generic.Decorators.InRangeHealth")
BehaviorTree.process["IsBehavior"] =                GFScript("AIModule.Generic.Decorators.IsBehavior")
BehaviorTree.process["IsSet"] =                     GFScript("AIModule.Generic.Decorators.IsSet")
BehaviorTree.process["HasBuff"] =                   GFScript("AIModule.Generic.Decorators.HasBuff")
BehaviorTree.process["HasStatValue"] =              GFScript("AIModule.Generic.Decorators.HasStatValue")
BehaviorTree.process["CanAttack"] =                 GFScript("AIModule.Generic.Decorators.CanAttack")
BehaviorTree.process["IsCasting"] =                 GFScript("AIModule.Generic.Decorators.IsCasting")
BehaviorTree.process["CheckActorId"] =              GFScript("AIModule.Generic.Decorators.CheckActorId")


BehaviorTree.process["WarriorService"] =           GFScript("AIModule.Generic.Services.WarriorService")
BehaviorTree.process["WalkerService"] =            GFScript("AIModule.Generic.Services.WalkerService")
BehaviorTree.process["PetService"] =               GFScript("AIModule.Generic.Services.PetService")

return GenericTree
