#!/usr/bin/env python3
"""
Setup Game Project

Usage:
    python setup_game_project.py <GAME_DIR>

Example:
    python setup_game_project.py projects/crystal-parkour
"""

import argparse
import shutil
import sys
from pathlib import Path


def get_project_root() -> Path:
    """Get the project root directory (parent of workflow/)."""
    script_dir = Path(__file__).resolve().parent  # workflow/Tools
    return script_dir.parent.parent  # workflow/ -> project root


def copy_empty_game_template(game_dir: Path, project_root: Path) -> bool:
    """
    Copies all files from workflow/Tools/emptygame to the game directory.
    """
    source_dir = project_root / "workflow" / "Tools" / "emptygame"

    # Validate source directory exists
    if not source_dir.exists():
        print(f"Error: Source directory not found: {source_dir}", file=sys.stderr)
        return False

    # Create destination directory if it doesn't exist
    if not game_dir.exists():
        print(f"Creating destination directory: {game_dir}")
        game_dir.mkdir(parents=True, exist_ok=True)

    print(f"Copying from: {source_dir}")
    print(f"Copying to: {game_dir}")

    try:
        # Copy all files and subdirectories
        for item in source_dir.iterdir():
            dest_item = game_dir / item.name
            if item.is_dir():
                if dest_item.exists():
                    shutil.rmtree(dest_item)
                shutil.copytree(item, dest_item)
            else:
                shutil.copy2(item, dest_item)

        print(f"Successfully copied emptygame template to {game_dir}")
        return True
    except Exception as e:
        print(f"Error: Failed to copy template: {e}", file=sys.stderr)
        return False


def copy_sgf_framework(game_dir: Path, project_root: Path) -> bool:
    """
    Copy SGF framework to GAME_DIR.

    Copies Framework directory and Framework.json from workflow/SGF/
    to GAME_DIR/ServiceNodes/MainStorage/.
    """
    source_framework_dir = project_root / "workflow" / "SGF" / "Framework"
    source_framework_json = project_root / "workflow" / "SGF" / "Framework.json"
    destination_main_storage = game_dir / "ServiceNodes" / "MainStorage"

    # Validate source directory and file exist
    if not source_framework_dir.exists():
        print(f"Error: Source Framework directory not found: {source_framework_dir}", file=sys.stderr)
        return False

    if not source_framework_json.exists():
        print(f"Error: Source Framework.json file not found: {source_framework_json}", file=sys.stderr)
        return False

    # Create destination MainStorage directory if it doesn't exist
    if not destination_main_storage.exists():
        print(f"Creating MainStorage directory: {destination_main_storage}")
        try:
            destination_main_storage.mkdir(parents=True, exist_ok=True)
            print("MainStorage directory created successfully")
        except Exception as e:
            print(f"Error: Failed to create MainStorage directory: {e}", file=sys.stderr)
            return False

    # Set destination paths
    destination_framework_dir = destination_main_storage / "Framework"
    destination_framework_json = destination_main_storage / "Framework.json"

    print(f"\nCopying SGF Framework from: {source_framework_dir}")
    print(f"Copying to: {destination_main_storage}")

    try:
        # Copy Framework folder
        if destination_framework_dir.exists():
            print("Removing existing Framework directory...")
            shutil.rmtree(destination_framework_dir)
        shutil.copytree(source_framework_dir, destination_framework_dir)
        print("Framework directory copied successfully")

        # Copy Framework.json file
        shutil.copy2(source_framework_json, destination_framework_json)
        print("Framework.json copied successfully")

        print(f"\nSuccessfully copied SGF Framework to {destination_main_storage}")
        return True
    except Exception as e:
        print(f"Error: Failed to copy SGF Framework: {e}", file=sys.stderr)
        return False


def create_data_directory(game_dir: Path) -> bool:
    """
    Creates GAME_DIR/UnitsData/ for storing all the intermediate data generated by workflow execution units.
    """
    data_dir = game_dir / "UnitsData"

    try:
        if not data_dir.exists():
            print(f"Creating data directory: {data_dir}")
            data_dir.mkdir(parents=True, exist_ok=True)
            print("data directory created successfully")
        else:
            print(f"data directory already exists: {data_dir}")
        return True
    except Exception as e:
        print(f"Error: Failed to create data directory: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Setup game project by copying templates and frameworks"
    )
    parser.add_argument(
        "game_dir",
        type=str,
        help="Path to the game directory (e.g., projects/crystal-parkour)"
    )

    args = parser.parse_args()

    # Get project root and resolve game directory path
    project_root = get_project_root()
    game_dir = Path(args.game_dir)

    # If game_dir is relative, make it relative to project root
    if not game_dir.is_absolute():
        game_dir = project_root / game_dir

    game_dir = game_dir.resolve()

    print("=" * 60)
    print("Game Project Setup")
    print("=" * 60)
    print(f"Project root: {project_root}")
    print(f"Game directory: {game_dir}")
    print("=" * 60)

    # Copy empty game template
    print("\nCopying empty game template...")
    if not copy_empty_game_template(game_dir, project_root):
        print("\nSetup failed", file=sys.stderr)
        sys.exit(1)

    # Copy SGF framework
    print("\nCopying SGF framework...")
    if not copy_sgf_framework(game_dir, project_root):
        print("\nSetup failed", file=sys.stderr)
        sys.exit(1)

    # Create data directory
    print("\nCreating data directory...")
    if not create_data_directory(game_dir):
        print("\nSetup failed", file=sys.stderr)
        sys.exit(1)

    # Report completion
    print("\n" + "=" * 60)
    print("Setup Complete!")
    print("=" * 60)
    print(f"Game directory: {game_dir}")
    print("- Empty game template copied")
    print("- SGF framework installed")
    print("- data directory created")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
